version: "3"

services:
  node:
    image: node:18.0.0-alpine
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/home/node

  postgresql:
    image: postgres:15.2-alpine3.17
    environment:
      POSTGRES_DB: $DATABASE_NAME
      POSTGRES_USER: $DATABASE_USER
      POSTGRES_PASSWORD: $DATABASE_PASSWORD